scoop-tech-corp/rpc-be

app/Http/Controllers/ApiController.php
app/Http/Controllers/DataStaticController.php
app/Http/Controllers/LocationController.php
routes/api.php
storage/api-docs/api-docs.json

rapiin get detail location , dan order by id, alamat

update get detail location

---

database/seeders/testing.php

adjust testing.php

---

app/Http/Controllers/ImportRegionController.php
storage/api-docs/api-docs.json

adjust bulk insert

---

app/Http/Controllers/ImportRegionController.php
storage/api-docs/api-docs.json

update swagger upload

---

app/Exports/exportFacility.php
app/Exports/exportValue.php

export change no

---

app/Exports/exportFacility.php
app/Exports/exportValue.php

change column name

---

app/Http/Controllers/LocationController.php
app/Http/Controllers/ProductController.php
database/migrations/2022_09_24_165346_product_supplier.php
database/migrations/2022_09_24_165528_product_status.php
database/migrations/2022_09_24_171115_product_reminder.php
database/migrations/2022_09_25_120011_product_brand.php
routes/api.php
storage/api-docs/api-docs.json

add swagger

---

app/Http/Controllers/FasilitasController.php
app/Http/Controllers/LocationController.php
routes/api.php

change to postman

---

app/Http/Controllers/LocationController.php

provinceId to provinceCode

---

app/Http/Controllers/ApiController.php
app/Http/Controllers/DataStaticController.php
app/Http/Controllers/FasilitasController.php
app/Http/Controllers/LocationController.php
database/migrations/2022_10_16_213309_create_users_role.php
database/migrations/2022_10_17_223638_update_location_email.php
database/seeders/testing.php

data static and type phone remove

data static and type phone remove

---

app/Http/Controllers/DataStaticController.php
app/Http/Controllers/FasilitasController.php
app/Http/Controllers/LocationController.php
database/seeders/LocationSeeder.php

PR location header

---

app/Http/Controllers/DataStaticController.php
app/Http/Controllers/FasilitasController.php
app/Http/Controllers/LocationController.php
database/migrations/2022_10_20_190918_create_image_location.php
database/migrations/2022_10_20_190933_drop_imageon_location.php
database/migrations/2022_10_20_234710_create_image_facility.php

update location facility and data static

---

app/Http/Controllers/DataStaticController.php
app/Http/Controllers/FacilityController.php
app/Http/Controllers/LocationController.php
database/migrations/2022_10_21_232834_update_nullable_detail_address.php
database/seeders/LocationSeeder.php
database/seeders/testing.php
routes/api.php

Notes hari ini
- Create folder image di public > FacilityImages
public > LocationImages
- End point di Postman sudah sesuai fix dan diberi token
- ada update seeder location , ga perlu dinaikan, karena cuman hapus is branch sama images dan imagePath, kemarin belum include
- FasiltasController sudah dichange jadi FacilityController, Route fasiltas sudah dichange, dan sudah berjalan dipostman
- Delete location,fasilitas sudah ditambah table images, dan semua bentuk array	, jadi bisa multiple			
- locationimages, fasilitasimages -> sudah apply hashname dan sudah masuk kedatabase, menggunakan formdata di postman, dan juga bisa double
- index location,fasilitas, datastatic sudah apply order by newest created data 
- untuk fasilitas ( update, delete ) pakai {facilityCode}, codeLocation pakai …

update location facility data static

---

app/Http/Controllers/LocationController.php

where clause

---

app/Http/Controllers/FacilityController.php
app/Http/Controllers/LocationController.php
database/migrations/2022_10_22_013007_update_facility_images.php
routes/api.php

-ada migrateion untuk location  facility images penambahan labelname asli sama name untuk search image yang udah pernah diupload
-route ada tambah untuk seach images location sama facilty
-function search images facility dan location
-penambahan attribut di post man pada saat insert menggunakan form data (imagesName)
format : note** kalau data images ada 2 , wajib buat 2 id gini
[
{
"id":1,
"name":"value"
},
{
"id":2,
"name":"asd"
}
]
-penambahan logic search untuk search ke table image location sama image facility, logic nya sama seperti header

notes 22102022

---

app/Http/Controllers/FacilityController.php
app/Http/Controllers/LocationController.php
routes/api.php

use all form data , update decode location and fasilitas , end point change dari put jadi post

use all form data

---

app/Http/Controllers/FacilityController.php
app/Http/Controllers/LocationController.php
database/migrations/2022_10_25_175505_update_location.php

1.alter location and address into longtext
2.location and facility check id when not deleted if, exists then not insert

update location and facility

---

app/Http/Controllers/FacilityController.php
app/Http/Controllers/LocationController.php

update upload image

---

app/Exports/exportFacility.php
app/Http/Controllers/FacilityController.php
database/migrations/2022_11_11_223132_update_new_facility.php
database/migrations/2022_11_11_224755_update_new_facility_unit.php
database/migrations/2022_11_12_161850_update_new_facility_images.php

Notes facility
-- migrate ada 3 , table facility , facility unit, facility images -- index automated tambah dari location yang dibuat, kalau location baru, difacility akan ada yang baru dengan amount 0 -- untuk penambahan/update/ delete unit setelah create facility pertama kali
ada "command" ins, untuk insert, del untuk delete, dan kosong untuk update/
-- validasi sudah berjalan unitname tidak boleh lebih 25 karakter, status harus diisi, kapasitas harus diisi,amount harus diisi, notes juga tidak bolehj lebih dari 300 -- untuk upload images masih sama dengan sebelumnya,(tidak menggunakan facility code-> diganti menjadi location name dan unit name yang didapat dari Search images / detail images)
kalau insert id kosong, dan status kosong
kalau delete id ada dan status del
kalau update id ada …

notes update facility 13112022

---

database/migrations/2022_11_11_224755_update_new_facility_unit.php
database/migrations/2022_11_12_161850_update_new_facility_images.php

change migrate into all drop column

change migrate

---

app/Http/Controllers/FacilityController.php
database/migrations/2022_09_04_163214_create_fasilitas_table.php
database/migrations/2022_09_06_200907_fasilitas_unit.php
database/migrations/2022_10_20_234710_create_image_facility.php

add location id

---

app/Http/Controllers/FacilityController.php

update require facility validator

update require facility validator

---

app/Http/Controllers/LocationController.php
database/migrations/2022_08_10_234112_create_locations_alamats_details_table.php

fix issue part 2

---

database/seeders/FacilitySeeder.php
database/seeders/LocationSeeder.php

change seeder location and facility

change seeder location and facility

---

app/Http/Controllers/ApiController.php
app/Models/User.php
database/seeders/testing.php

Model user add is Deleted

---

app/Http/Controllers/ApiController.php
app/Http/Controllers/FacilityController.php

facility update locationname

---

app/Http/Controllers/Product/ProductClinicController.php
app/Http/Controllers/Product/ProductController.php
app/Http/Controllers/Product/ProductInventoryController.php
app/Http/Controllers/Product/ProductSellController.php
app/Models/ProductClinicDosage.php
app/Models/ProductInventory.php
app/Models/ProductInventoryList.php
app/Models/ProductInventoryListImages.php
database/migrations/2022_11_27_182203_create_product_inventory_lists_table.php
database/migrations/2023_01_10_232145_create_product_clinic_dosages_table.php
database/migrations/2023_01_11_222340_create_product_inventory_list_images_table.php
routes/api.php

- Add Data Product Clinic
- Update Drop Down Product Clinic
- Update Index Product Sell and Clinic

Enhancement

---

app/Http/Controllers/Product/BundleController.php
app/Http/Controllers/Product/ProductClinicController.php
app/Http/Controllers/Product/ProductInventoryController.php
app/Http/Controllers/Product/ProductSellController.php

Fixing Search Bundle, and validation
Update Product detail

Fixing and Update Detail

---

app/Http/Controllers/ApiController.php
database/seeders/User/userSeeder.php

user seeder update

---

app/Exports/Product/DataRecapSupplier.php
app/Exports/Product/SupplierReport.php
app/Http/Controllers/Product/RestockController.php
app/Http/Controllers/Product/SupplierController.php
app/Models/productRestockDetails.php
app/Models/productRestocks.php
composer.lock
database/migrations/2023_06_23_010053_change_approval_restock_to_restock_detail.php
routes/api.php

- fixing restock tabel
- add index restock new feature
- export product supplier

Updating Several menu

---

app/Helpers/helpers.php
app/Http/Controllers/Product/ProductClinicController.php
app/Http/Controllers/Product/ProductSellController.php
app/Http/Controllers/Product/RestockController.php
app/Models/productClinicBatch.php
app/Models/productRestockDetails.php
app/Models/productRestockImageReceive.php
app/Models/productSellBatch.php
database/migrations/2023_06_30_155343_add_reason_cancel_at_productrestockdetails.php
database/migrations/2023_06_30_171455_create_product_sell_batches_table.php
database/migrations/2023_06_30_171502_create_product_clinic_batches_table.php
database/migrations/2023_07_01_160139_create_product_restock_image_receives_table.php
routes/api.php

- add product batch
- add reason cancel in restock detail
- add confirm receive logic

Depoying new Feature

---

app/Helpers/helpers.php
app/Http/Controllers/Product/TransferProductController.php
app/Models/ProductTransferLog.php
database/migrations/2023_07_27_022657_create_product_transfer_logs_table.php
routes/api.php

- Enhance Index Product Transfer
- Enhance Detail Transfer Product

Update Product Transfer

---

app/Http/Controllers/Product/RestockController.php
app/Http/Controllers/Staff/AbsentController.php
app/Http/Controllers/Staff/ProfileController.php
database/migrations/2023_08_12_221650_update_users_table_add_username_imagepath.php
database/migrations/2023_08_13_111222_remove_column_access_limit_id_in_access_control.php

- validation absent
- fixing photo profile

Add in Staff Module

---

app/Http/Controllers/Customer/DataStaticCustomerController.php

Change source Customer to Source Reminder

Data Static Customer

---

app/Helpers/helpers.php
app/Http/Controllers/Customer/CustomerController.php
app/Http/Controllers/DashboardController.php
app/Http/Controllers/Product/BundleController.php
app/Http/Controllers/Product/ProductClinicController.php
app/Http/Controllers/Product/ProductInventoryController.php
app/Http/Controllers/Product/ProductSellController.php
app/Http/Controllers/StaffController.php

Add new for Modulee:
- staff list
- customer
- dashboard

Enhance User Access Control

---

app/Helpers/helpers.php
app/Http/Controllers/Customer/CustomerController.php
app/Http/Controllers/Customer/ImportCustomerController.php
app/Http/Controllers/Transaction/TransactionController.php
app/Models/Customer/CustomerPets.php
app/Models/TransactionLog.php
database/migrations/2024_12_28_150424_create_transaction_logs_table.php
database/migrations/2024_12_29_115203_add_column_created_customer_pets.php
routes/api.php

add transaction log
add detail
add update feature transaction

module transaction

---

app/Http/Controllers/Transaction/TransactionController.php
app/Models/TransactionPetCheck.php
database/migrations/2025_01_18_142236_create_transaction_pet_checks_table.php
routes/api.php

- add new endpoint check hpl
- adjust column pet check
- adjust index transaction

Add Check Pet

---

app/Exports/Product/DataRecapProductTransfer.php
app/Http/Controllers/Product/TransferProductController.php
app/Http/Controllers/Service/ServiceController.php

- fixing update service
- fixing generate excel transfer product

Fixing several feature

---

app/Http/Controllers/Transaction/TransactionPetClinicController.php
app/Models/TransactionPetClinic.php
app/Models/TransactionPetClinicAdvice.php
app/Models/TransactionPetClinicCheck.php
app/Models/TransactionPetClinicCheckUpResult.php
app/Models/TransactionPetClinicDiagnose.php
app/Models/TransactionPetClinicTreatment.php
database/migrations/2025_04_21_083624_create_transaction_pet_clinics_table.php
database/migrations/2025_04_21_084050_create_transaction_pet_clinic_checks_table.php
database/migrations/2025_04_22_083436_create_transaction_pet_clinic_check_up_results_table.php
database/migrations/2025_04_22_083638_create_transaction_pet_clinic_diagnoses_table.php
database/migrations/2025_04_22_083753_create_transaction_pet_clinic_treatments_table.php
database/migrations/2025_04_22_083911_create_transaction_pet_clinic_advice_table.php
routes/api.php

- Create and Index API
- Table pet check condition

Transaction Pet Clinic
